#
# See default configuration here: https://github.com/codecov/support/blob/master/codecov.yml
#
# For more options see: https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a
#
# Codecov documentation is available here: https://codecov.io/docs

coverage:
  ignore:
  - generated/*
  - test/*
  - testutil/src/main/java/io/spine/examples/todolist/testdata/*
  - cli/src/main/java/io/spine/examples/todolist/mode/*
  - cli/src/main/java/io/spine/examples/todolist/CliEntryPoint.java

  status:
    patch: false

comment:
  layout: "header, diff, changes, uncovered"
