language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  # Decrypt the Firebase service account secret with Travis-private environmental variables.
  - openssl aes-256-cbc -K $encrypted_1c1c75fb6aea_key -iv $encrypted_1c1c75fb6aea_iv -in ./firebase-mirror/src/test/resources/serviceAccount.json.enc -out ./firebase-mirror/src/test/resources/serviceAccount.json -d

script:
  - ./gradlew build codeCoverageReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
