language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_1c1c75fb6aea_key -iv $encrypted_1c1c75fb6aea_iv -in ./firebase-repeater/src/test/resources/serviceAccount.json.enc -out ./firebase-repeater/src/test/resources/serviceAccount.json -d

script:
  - ./gradlew build --stacktrace
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
