language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_aa93bcacb4f5_key -iv $encrypted_aa93bcacb4f5_iv -in spine-dev.json.enc -out spine-dev.json -d
  - mkdir ./deployment/appengine-web/src/main/resources
  - mv ./spine-dev.json ./deployment/appengine-web/src/main/resources/spine-dev.json

script:
  - ./gradlew check --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
