language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_aa93bcacb4f5_key -iv $encrypted_aa93bcacb4f5_iv -in spine-dev.json.enc -out spine-dev.json -d
  - mkdir ./deployment/appengine-web/src/main/resources
  - mv ./spine-dev.json ./deployment/appengine-web/src/main/resources/spine-dev.json

# Skip the `install` step.
install: true

script:
  - ./gradlew assemble check --info --stacktrace -PbuildProfile=dev
  - ./gradlew :appengine-web:war

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: gae
  config: deployment/appengine-web/build/exploded-appengine-web/WEB-INF/appengine-web.xml
  keyfile: deployment/appengine-web/src/main/resources/spine-dev.json
  # When changing the project don't forget to update `-PbuildProfile` parameter in `script` section.
  project: spine-dev
  # The artifacts created when executing Travis scripts section are required
  # to deploy the application. The cleanup is disabled to preserve these generated artifacts.
  skip_cleanup: true
  # Enable `master` branch filter after CI deployment adjustments
  on:
    branch: appengine-deploy
