# To-do List application Travis CI Build configuration.
#
# Uses Travis build stages to organize build and deployment processes.
# See https://docs.travis-ci.com/user/build-stages/ for details.
#
stages:
  - Unit and Integration Tests
  - name: Deployment
    #if: branch = master AND type != pull_request //Enable this stage on merge into master branch
    if: branch = appengine-deploy
jobs:
  include:

    # The objective of this stage is to assemble the project and
    # to run unit and integration tests with coverage
    #
    - stage: Unit and Integration Tests
      language: java
      jdk:
        - oraclejdk8
      before_install:
        - chmod +x gradlew
        - openssl aes-256-cbc -K $encrypted_aa93bcacb4f5_key -iv $encrypted_aa93bcacb4f5_iv -in spine-dev.json.enc -out spine-dev.json -d
        - mkdir ./deployment/appengine-web/src/main/resources
        - mv ./spine-dev.json ./deployment/appengine-web/src/main/resources/spine-dev.json
      # Skip the `install` step as described here https://docs.travis-ci.com/user/job-lifecycle/.
      install: true
      script:
        - ./gradlew assemble check --info --stacktrace
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    # The objective of this stage is to  deploy the To-do List application to the
    # AppEngine Standard environment. See `appengine-web/README.md` for details.
    #
    - stage: Deployment
      language: java
      jdk:
        - oraclejdk8
      before_install:
        - chmod +x gradlew
      # Skip the `install` step as described here https://docs.travis-ci.com/user/job-lifecycle/.
      install: true
      script:
        # Install Google App Engine SDK packages for Java. These components are used by Gradle
        # App Engine plugin to deploy a Java application to App Engine.
        - gcloud components install app-engine-java
        - ./gradlew :appengine-web:war -PbuildProfile
        - ./gradlew :appengine-web:appengineDeploy -PbuildProfile
