#
# API configuration of Google Cloud Endpoints
#
# Below, replace MY_PROJECT_ID with your Google Cloud Project ID.
#

# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: hellogrpc.endpoints.MY_PROJECT_ID.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: ToDOList Cloud Endpoints

apis:
  - name: spine.client.CommandService
  - name: spine.client.QueryService
  - name: spine.client.SubscriptionService
